name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      stack:
        description: Destroy in dependency order (ec2 → iam → sg → vpc)
        required: true
        type: choice
        options:
          - ec2
          - iam
          - sg
          - vpc

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev/${{ github.event.inputs.stack }}

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - run: terraform destroy -auto-approve