name: Terraform PR Checks

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stack:
          - vpc
          - sg
          - iam
          - ec2

    defaults:
      run:
        working-directory: environments/dev/${{ matrix.stack }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color